name: dcase24
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python==3.11.9
  - pytorch=2.3.1=py3.11_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8
  - torchaudio=2.3.1=py311_cu118
  - torchvision=0.18.1=py311_cu118
  - lightning=2.3.3
  - pip=24.0
  - transformers=4.42.4
  - scikit-learn=1.5.1
  - librosa=0.10.2
  - torchinfo=1.8.0
  - pip:
    - hear21passt==0.0.26
    - wandb==0.17.5